# Generated by Django 5.2 on 2026-01-26 02:56

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PASS', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=20, verbose_name='Número de documento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('country', models.CharField(default='Colombia', max_length=50, verbose_name='País')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto de perfil')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='Suscrito a newsletter')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
